Exo:
  parameter: '0.2'
  reactions:
  - - - &id001
        - input
        - 0
    - []
    - 1
  species: []
PEN:
  parameter: '0.2'
  reactions:
  - - - *id001
      - &id002
        - template
    - - &id004
        - template_in
    - mm_rate
  - - - *id001
      - *id002
    - - &id003
        - template_out
    - 1
  - - - *id001
      - *id003
    - - &id005
        - template_both
    - 1
  - - - *id001
      - *id004
    - - *id005
    - 1
  - - - *id004
    - - *id001
      - *id002
    - 1
  - - - *id003
    - - *id001
      - *id002
    - 1
  - - - *id005
    - - *id001
      - *id003
    - 1
  - - - *id005
    - - *id001
      - *id004
    - 1
  - - - *id004
    - - &id006
        - template_ext
    - 1
  - - - *id005
    - - *id006
      - *id001
    - 1
  - - - *id006
    - - *id005
    - 1
  - - - *id002
    - - *id003
    - 1
  species:
  - template_in
  - template_out
  - template_both
  - template_ext
PP:
  parameter: '0.2'
  reactions:
  - - - *id001
      - *id002
    - - *id004
    - 1
  - - - *id004
    - - *id001
      - *id002
    - 1
  - - - *id006
    - - *id002
      - *id002
    - 1
  - - - *id004
    - - *id006
    - 1
  species:
  - template_in
  - template_ext
